project:
  type: book
  execute-dir: project
  output-dir: docs

book:
  title: "Julia for Deep Learning"
  subtitle: "Companion book of the [Julia for Deep Learning Course](https://github.com/cpfiffer/julia-deeplearning)"
  author: 
    - name: Patrick Altmeyer
      email: p.altmeyer@tudelft.nl
      affiliation:
        - name: Delft University of Technology
          city: Delft
          state: North-Holland
          url: https://www.tudelft.nl/
    - name: Cameron Pfiffer
      email: cameron@pfiffer.org
      affiliation: 
        - name: Stanford University
          city: Stanford
          state: CA
          url: www.stanford.edu
  date: today
  chapters:
    - index.qmd
    - intro.qmd
    - chapters/c4.qmd
    - summary.qmd
    - contributors.qmd
    - references.qmd

  favicon: logo.png
  cover-image: logo.png
  repo-url: https://github.com/pat-alt/julia-deeplearning-book
  repo-actions: [edit, issue]
  search: true
  sharing: [twitter]
  twitter-card: true

bibliography: references.bib

format:
  julia-html: default

jupyter: julia-1.9



