[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FastAI = "5d0beca9-ade8-49ae-ad0b-a3cf890e669f"
FastMakie = "ca994201-3d74-4fad-8816-f8bc5449c7c3"
FastTabular = "d896c661-108c-409d-a26f-7fe446e2d3d3"
FastVision = "7bf02486-ff4c-4e73-b158-40c00866b54f"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
FreeType = "b38be410-82b0-50bf-ab77-7b57e271db43"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
MLDatasets = "eb30cadb-4394-5ae3-aed4-317e484a6458"
MLUtils = "f1d291b0-491e-4a28-83b9-f70985020b54"
Measures = "442fdcdd-2543-5da2-b0f3-8c86c306513e"
Metalhead = "dbeba491-748d-5e0e-a39e-b530a07fa0cc"
OneHotArrays = "0b1bfda6-eb8a-41d2-88d8-f5af5cad476f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
